### ISSUE TITLE
Allow loading of remote styles

### ISSUE THREAD

**Issue by fcheslack** [zotero/citeproc-node#18]
Accept remote style url to fetch and cache.
Use initialized engine for current request and cache like other engines for subsequent requests.

**Comment by rmzelle** [comment]
Is this possible now in the Zotero API?

**Comment by rmzelle** [comment]
(I've been asked again to please, please accept a style into the repo so a university can use their custom style for their Zotero API-generated bibliographies, and I much rather wouldn't since the style would have a single user and doesn't really belong in the CSL styles repo. I could accept it temporary, but that has some drawbacks as well (like repo bloat).)

**Comment by rmzelle** [comment]
(and we've decline half a dozen similar Zotero-API styles in the past, so the demand is clearly there)

**Comment by fcheslack** [comment]
It is not yet.

https://github.com/zotero/dataserver/issues/24

**Comment by rmzelle** [comment]
And now? :) (since https://github.com/zotero/dataserver/issues/24 was just closed)

I guess not since, since https://api.zotero.org/users/475425/items/X42A7DEE?format=bib&style=apa works for me, but https://api.zotero.org/users/475425/items/X42A7DEE?format=bib&style=https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl gives "Invalid style"?

**Comment by dstillman** [comment]
We'll announce when that's live on the dev list. Should be in the next week or so.

**Comment by rmzelle** [comment]
Great, thanks.
